# ===== Controller Timing =====
CONTROLLER_INIT_WAIT = 1.0
JOINT_MOVE_DURATION = 1.5
MOVE_TO_DURATION = 3.0
OPEN_GRIPPER_DURATION = 0.5
CLOSE_GRIPPER_DURATION = 1.0
ALIGN_GRIPPER_DURATION = 1.0
RESET_DURATION = 3.0
GRIPPER_DOWN_DURATION = 1.0

# ===== Gripper Finger Positions =====
GRIPPER_OPEN_POS = (-0.02, 0.02, 0.02, -0.02)
GRIPPER_CLOSE_POS = (0.02, -0.02, -0.02, 0.02)

# ===== Reset Pose =====
RESET_THETA1 = 0.0
RESET_THETA2 = 0.0
RESET_D3 = 0.0
RESET_GRIPPER_ROLL = 0.0

# ===== Gripper Down =====
# 夹爪下降安全间距
GRIPPER_DOWN_SAFE_OFFSET = 0.206